# Generated by Django 3.0.6 on 2020-05-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='file',
            field=models.FileField(upload_to='ducuments/'),
        ),
    ]
