# Generated by Django 3.0.6 on 2020-05-11 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileManager', '0003_auto_20200511_0446'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Profile',
            new_name='Video',
        ),
    ]
