# Generated by Django 3.0.6 on 2020-05-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileManager', '0004_auto_20200511_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
