# Generated by Django 2.2.8 on 2020-07-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='type_of_course',
            field=models.IntegerField(choices=[(4, 'momtaz'), (3, 'Awli'), (2, 'khosh'), (1, 'motevaset'), (0, 'test')], default=0, max_length=2),
        ),
    ]
