# Generated by Django 2.2.8 on 2020-07-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManager', '0002_course_type_of_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type_of_profile',
            field=models.CharField(choices=[('te', 'momtaz'), ('st', 'Awli')], default='st', max_length=2),
        ),
    ]
