# Generated by Django 2.2.8 on 2020-07-22 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userManager', '0003_profile_type_of_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.IntegerField()),
                ('student_id', models.IntegerField()),
                ('file_teacher', models.FileField(upload_to='assignments/')),
                ('file_student', models.FileField(upload_to='answers/')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='course',
            name='type_of_course',
            field=models.IntegerField(choices=[(4, 'momtaz'), (3, 'Awli'), (2, 'khosh'), (1, 'motevaset'), (0, 'test')], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='userManager.Course'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type_of_profile',
            field=models.CharField(choices=[('te', 'teacher'), ('st', 'student')], default='st', max_length=2),
        ),
    ]
