# Generated by Django 2.2.8 on 2020-07-22 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManager', '0005_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
