# Generated by Django 2.2.8 on 2020-07-23 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManager', '0007_auto_20200723_0356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='teacher_id',
            new_name='teacher',
        ),
    ]
