# Generated by Django 2.2.8 on 2020-07-23 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManager', '0008_auto_20200723_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='title',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
