# Generated by Django 2.2.8 on 2020-07-23 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userManager', '0009_assignment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='file_student',
            field=models.FileField(blank=True, upload_to='answers/'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='file_teacher',
            field=models.FileField(blank=True, upload_to='assignments/'),
        ),
    ]
