# Generated by Django 2.2.8 on 2020-07-23 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManager', '0010_auto_20200723_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='course',
        ),
    ]
