# Generated by Django 2.2.8 on 2020-07-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManager', '0015_auto_20200723_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
