# Generated by Django 2.2.8 on 2020-07-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManager', '0018_ticket_ticket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='type_of_course',
            field=models.IntegerField(choices=[(5, 'none'), (4, 'momtaz'), (3, 'Awli'), (2, 'khosh'), (1, 'motevaset'), (0, 'test')], default=5),
        ),
    ]
